### ISSUE TITLE
Post view

### ISSUE THREAD

**Issue by Zaturrby** [simulacrum-amsterdam/simulacrum-sage#19]
![img_6863](https://cloud.githubusercontent.com/assets/7668506/10263227/71d4f67c-69e6-11e5-921a-6eed5fb75dab.JPG)

**Comment by Zaturrby** [comment]
Scientific nature less important. Versioning / Peer review can be dropped. Personal component important.

**Comment by Zaturrby** [comment]
![schermafbeelding 2015-10-24 om 12 34 44](https://cloud.githubusercontent.com/assets/7668506/10710152/9f2dab9e-7a4b-11e5-90a8-cfc52f44450d.png)

I actually like the image fullscreen in the background! It need a "show" button though. The content hides the images now.

**Comment by Zaturrby** [comment]
(and the texture needs to improve)

**Comment by Zaturrby** [comment]
Thinking of doing the buttons is the right upper corner, outside the post perhaps. But then they'll need a bit of margin

**Comment by Zaturrby** [comment]
show/hide button will go in with a simple transition and a good texture

**Comment by Zaturrby** [comment]
![schermafbeelding 2015-10-25 om 20 02 29](https://cloud.githubusercontent.com/assets/7668506/10717296/5bb012c2-7b53-11e5-833f-0a1f1855a459.png)
![schermafbeelding 2015-10-25 om 20 02 33](https://cloud.githubusercontent.com/assets/7668506/10717297/5cc8e9fe-7b53-11e5-92af-eea53b20437f.png)

Post hoeft niet perse een kopie van plaatje te bevatten.

**Comment by Zaturrby** [comment]
De afbeeldingen trekken wel echt aandacht zo en lokken uit om bestudeerd te worden, gewoonweg omdat ze lomp groot zijn. I like it. Maar er zit nog wel een bug aan de footer doordat dit gevaarte buiten de documentflow zit.

**Comment by Zaturrby** [comment]
BUGS: zodra er geen afbeelding is en zodra er een te lange is met de footer

**Comment by Zaturrby** [comment]
Extra behaviour. Start at bottom.

**Comment by Zaturrby** [comment]
When to parse the background image divs needs to depend on the image, not the is_singular check.

**Comment by Zaturrby** [comment]
Same check needs to pop the button.

**Comment by Zaturrby** [comment]
There is still trouble with the setting of the position of the post box. (on-window-resize needs an eventlistener). Besides the extremely long images cause trouble. Perhaps one could rely on common sense not to put an extremely narrow image in the background, but there might also be some possible css control by setting max-heights on the elements.

**Comment by Zaturrby** [comment]
The writer and the post should be connected to each other, on post with long bg-images or very short posts they can disconnect from each other. (invisible container element)

**Comment by noraveerman** [comment]
De post view vind ik op dit moment echt prachtig. 

Zou misschien alles links uitlijnen in plaats van titel en locatie te centreren, maar dat is een detail. 
Mooi ook met die verwijzing naar de auteur onderaan!

**Comment by Zaturrby** [comment]
Ah, hier ook een post (die had ik nog even gemist) -> Titel en locatie moeten idd uitgelijnd. Dat zijn die ongemakkelijkheden in de database die ik bedoelde. Binnen dat vierkant heeft niet mijn code, maar de Wordpress administratieve interface de controle.

**Comment by Zaturrby** [comment]
Drie bugs hier nog
1. Uniforme conditional
2. CSS controle over achtergrond afbeeldingen
3. Images-loaded (javascript reageert met het neerzetten van de hoogte voordat de afbeeldingen geladen zijn)
