### ISSUE TITLE
Nav-top

### ISSUE THREAD

**Issue by Zaturrby** [simulacrum-amsterdam/simulacrum-sage#24]
I'm starting to get why people think side navigation should be an anti-pattern. Things that could be one click are now two. Maybe reconsider (limited) header navigation.

**Comment by Zaturrby** [comment]
![img_6864](https://cloud.githubusercontent.com/assets/7668506/10282361/ad1755b4-6b7a-11e5-8765-b06a639376ac.JPG)

**Comment by Zaturrby** [comment]
#27 It should provide some header tekst

**Comment by Zaturrby** [comment]
![schermafbeelding 2015-10-06 om 15 47 29](https://cloud.githubusercontent.com/assets/7668506/10310303/9532841a-6c41-11e5-993e-7f55f4eeeca6.png)
![schermafbeelding 2015-10-06 om 15 47 19](https://cloud.githubusercontent.com/assets/7668506/10310309/98205bc0-6c41-11e5-8b78-fd53499f045f.png)

**Comment by Zaturrby** [comment]
![schermafbeelding 2015-10-06 om 22 17 32](https://cloud.githubusercontent.com/assets/7668506/10321276/0ea04158-6c78-11e5-8625-fe36e1cc9a7f.png)

**Comment by Zaturrby** [comment]
Issues can go to the top of the navigation I think, make much more sense than to reserve a full sidebar for them. 
![img_6892](https://cloud.githubusercontent.com/assets/7668506/10687691/37c99b66-796f-11e5-9c95-16f4d80702cb.JPG)

**Comment by Zaturrby** [comment]
![schermafbeelding 2015-10-23 om 17 02 14](https://cloud.githubusercontent.com/assets/7668506/10698459/6bc58f00-79b1-11e5-932b-c957f28fad0d.png)

**Comment by Zaturrby** [comment]
Texture aan de bovenkant maakt het een stuk diverser. Texture zelf is niet zo geweldig, maar het idee is volgens mij wel goed.

**Comment by Zaturrby** [comment]
![schermafbeelding 2015-10-25 om 20 04 01](https://cloud.githubusercontent.com/assets/7668506/10717299/98b303fa-7b53-11e5-8464-11d973605b71.png)

Vind dit om zijn simpliciteit mooi. Denk dat ik hem erin hou. Maar het is eigenlijk een bug. De dubbele lijn.

**Comment by Zaturrby** [comment]
![schermafbeelding 2015-10-25 om 20 48 40](https://cloud.githubusercontent.com/assets/7668506/10717488/cb8d9190-7b59-11e5-9cbb-a63c061ac748.png)

**Comment by Zaturrby** [comment]
![schermafbeelding 2015-10-25 om 21 22 13](https://cloud.githubusercontent.com/assets/7668506/10717644/92b04c14-7b5e-11e5-9379-3b1d5680b4fd.png)

**Comment by Zaturrby** [comment]
![schermafbeelding 2015-10-25 om 21 36 08](https://cloud.githubusercontent.com/assets/7668506/10717703/6e3b2d66-7b60-11e5-9bb2-6ece2ab0f8d1.png)

**Comment by Zaturrby** [comment]
![schermafbeelding 2015-10-25 om 21 53 16](https://cloud.githubusercontent.com/assets/7668506/10717778/d3c61f7c-7b62-11e5-897e-9924d0d378a2.png)

**Comment by Zaturrby** [comment]
![schermafbeelding 2015-10-26 om 11 14 40](https://cloud.githubusercontent.com/assets/7668506/10726399/ca136c58-7bd2-11e5-87b9-55fd900928f3.png)

Starting to really like this weird typography

**Comment by Zaturrby** [comment]
About link is missing on small views. The big S replaces portal, but you cannot get to about.

**Comment by noraveerman** [comment]
Hai Robert-Jan! Vind het blog mooi met die horizontale foto's. Wel is het misschien handiger als die een iets ander formaat hebben, want dit vraagt veel van de kwaliteit en het type foto. Dat maakt het zoeken naar een geschikt plaatje weer zo'n opgave. Denk ook dat het toch mooier is om het blog iets naar links te plaatsen en aan de rechterkant nog een zijbalk te hebben voor oude nummers e.d. 
Vind het ontwerp nu wel heel vet, maar misschien dat het ook nog iets conservatiever kan; iets meer vasthouden aan een 'ouderwetse' website-indeling maakt de onderdelen van de website denk ik wel makkelijker te vinden voor zoekers. 

Ik gooi er nog even een website in waar ik echt fan van ben: mooie navigatie aan de bovenkant, bijvoorbeeld. Deze is dan wel weer vrij eenvoudig, vind de speling met foto's en grotere en kleinere letters op de huidige Simulacrum website dan weer wel toffer. 
http://www.internationaleonline.org/

**Comment by noraveerman** [comment]
Eigenlijk vond ik je eerste voorstel wel goed! Iets hogere foto's, eenvoudige navigatie, balk aan de rechterkant. Die is ook prettig in gebruik, denk ik.

**Comment by noraveerman** [comment]
Denk dat de S nog wel iets groter kan, die mag evt ook wel een beetje uit de balk steken

**Comment by Zaturrby** [comment]
De internationale site is idd. goed uitgewerkt. Vooral de typografie is over nagedacht, hoewel misschien wel een beetje te klassiek voor ons. Fonts met schreef zijn afgewisseld met fonts zonder. Ook leeft de site mooi op als je over posts gaat met de muis. Misschien moeten wij nog even kijken of we wat met typografie kunnen doen, en of we het misschien net iets meer in balans kunnen brengen met andere elementen.  De content strategie is ook heel goed uitgedacht. Ze hebben goed nagedacht over hoe ze hun content categoriseren en presenteren. De informatiedichtheid voelt ook goed aan. \

Bij ons denk ik dat de informatiedichtheid soms dat die wat laag is, daarom heb ik de plaatjes klein gedrukt. Internationale zet 4 posts in één view. De sidebar heb ik om dezelfde reden een beetje verplaatst. Er was niet bijzonder veel inhoud, de plaatjes van de nummers moesten de hele sidebar trekken. Dit leek een mooie middenweg. Hoewel de sidebar een bekend patroon is, zorgt het ook voor veel loze ruimte als je naar beneden scrolt. 

Die S kunnen we trouwens ter plekke zo even mee spelen. Ik heb het even snel uitgeprobeerd, met deze dikke balk pakt het niet echt mooi uit. Maar met een dunnere... Een mooie rij links ben ik trouwens wel voor. Waar ze naartoe moeten linken ben ik wel wat onzekerder over… We hebben niet echt duidelijke rubrieken zoals Internationale Online. Maar ik heb sowieso een oplossing voor ‘Over’ op de kleine views nodig. 

![4](https://cloud.githubusercontent.com/assets/7668506/10833264/f496d1ac-7e90-11e5-8cda-4686a0c73795.png)
![2](https://cloud.githubusercontent.com/assets/7668506/10833265/f4988056-7e90-11e5-9ee7-8f432e0f4a0d.png)
![1](https://cloud.githubusercontent.com/assets/7668506/10833267/f49f8bbc-7e90-11e5-90d2-04466672218b.png)
![3](https://cloud.githubusercontent.com/assets/7668506/10833266/f49df234-7e90-11e5-83ed-2c3a77bb455c.png)
![5](https://cloud.githubusercontent.com/assets/7668506/10833268/f49fd658-7e90-11e5-9107-b0bf865c53d9.png)

**Comment by Zaturrby** [comment]
De voetnoten van internationale zijn trouwens ook heel mooi gedaan! Ohja; voor content layout op de frontpagina gebruiken ze een variant van http://masonry.desandro.com/ , wel interessant om even na te kijken; je kan er leuke dingen mee maken.

**Comment by Zaturrby** [comment]
De dikke navigatiebalk moet gaan splitten om meerder links mogelijk te maken.

**Comment by Zaturrby** [comment]
![schermafbeelding 2015-11-12 om 07 14 52](https://cloud.githubusercontent.com/assets/7668506/11111890/ca0acda8-890d-11e5-9264-a24450d48bf7.png)
![schermafbeelding 2015-11-10 om 18 07 38](https://cloud.githubusercontent.com/assets/7668506/11111891/ca0ced5e-890d-11e5-943e-f206bcba6669.png)
![schermafbeelding 2015-11-10 om 18 03 58](https://cloud.githubusercontent.com/assets/7668506/11111892/ca241d8a-890d-11e5-88b4-6e8f50c602ea.png)
